### ISSUE TITLE
Curious why put isn't included?

### ISSUE THREAD

**Issue by bgraner** [cmckni3/RestKit-PromiseKit#2]
Hey, just curious why put wasn't included in list of calls added to the category?

**Comment by cmckni3** [comment]
Interesting, I missed that method. You should open a pull request to add it. 😀

I really need to figure out a better way to wrap RestKit with promises as well.

**Comment by bgraner** [comment]
Actually I think this is a pretty good way.  If I have time I'll put some thought into it as well and help.

**Comment by bgraner** [comment]
Added https://github.com/cmckni3/RestKit-PromiseKit/pull/3

**Comment by cmckni3** [comment]
Thanks! I'll close this for now and look at the PR.

Feel free to open an issue with suggestions for improvements.
